{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/nilearn/datasets/__init__.py:86: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.\n",
      "  warn(\"Fetchers from the nilearn.datasets module will be \"\n",
      "/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari_animation/_qt/keyframeslist_widget.py:156: FutureWarning: Themes were changed to use evented model with Pydantic's color type rather than the `rgb(x, y, z)`. The `as_dict=True` option will be changed to `as_dict=False` in 0.4.15\n",
      "  self.setStyleSheet(template(qss_template, **get_theme(theme_name)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<OpenFile 'https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_0.35_100um//191815_00001_CH1.tif'>\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_0.35_100um//191815_00001_CH1.tif> \n",
      "\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_3.5_100um//191815_00001_CH1_resample.tif> \n",
      "\n",
      "Meta: {'name': 'mouseID_362188-191815', 'scale': (100, 0.35, 0.35), 'multiscale': True, 'contrast_limits': [0, 65535]}, data: (109, 28001, 19868)\n",
      "Meta: {'name': 'ilastik mask', 'scale': (100, 0.35, 0.35), 'multiscale': True}, data: (109, 28001, 19868)\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_3.5_100um//191815_00001_CH1_resample.tif> \n",
      "\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_0.35_100um//191815_00001_CH1.tif> \n",
      "\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_0.35_100um//191815_05401_CH1.tif> \n",
      "\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_3.5_100um//191815_05401_CH1_resample.tif> \n",
      "\n",
      "Reading viterbrain object\n",
      "Changing fragment path\n",
      "tracing from [   54 17553 13759] to [   54 17553 13759]\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_0.35_100um//191815_05501_CH1.tif> \n",
      "\n",
      "Reading <File-like object HTTPFileSystem, https://download.brainimagelibrary.org/df/75/df75626840c76c15/mouseID_362188-191815/CH1_3.5_100um//191815_05501_CH1_resample.tif> \n",
      "\n",
      "Reading viterbrain object\n",
      "Changing fragment path\n",
      "tracing from [   54 17553 13759] to [   54 17769 13527]\n",
      "Reading viterbrain object\n",
      "Changing fragment path\n",
      "tracing from [   54 17701 13459] to [   54 17557 13214]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (16966, 25448) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/containers/qt_layer_model.py\", line 42, in setData\n",
      "    self.getItem(index).visible = value\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 488, in visible\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/containers/qt_layer_model.py\", line 42, in setData\n",
      "    self.getItem(index).visible = value\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 488, in visible\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/containers/qt_layer_model.py\", line 42, in setData\n",
      "    self.getItem(index).visible = value\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 488, in visible\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/app/backends/_qt.py\", line 897, in paintGL\n",
      "    self._vispy_canvas.events.draw(region=None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 453, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    _handle_exception(self.ignore_callback_errors,\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/vispy/util/event.py\", line 469, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/qt_viewer.py\", line 982, in on_draw\n",
      "    layer._update_draw(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1579, in _update_draw\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_qt/containers/qt_layer_model.py\", line 42, in setData\n",
      "    self.getItem(index).visible = value\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 488, in visible\n",
      "    self.refresh()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/layers/base/base.py\", line 1173, in refresh\n",
      "    self.events.set_data()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 107, in _on_data_change\n",
      "    self._set_node_data(self.node, self.layer._data_view)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 119, in _set_node_data\n",
      "    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)\n",
      "  File \"/Users/thomasathey/Documents/mimlab/mouselight/docs_env/lib/python3.8/site-packages/napari/_vispy/layers/image.py\", line 224, in downsample_texture\n",
      "    raise ValueError(\n",
      "ValueError: Shape of in dividual tiles in multiscale (11164, 16745) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.\n"
     ]
    }
   ],
   "source": [
    "import napari\n",
    "import PIL.Image\n",
    "import numpy as np\n",
    "from napari_animation import AnimationWidget\n",
    "\n",
    "PIL.Image.MAX_IMAGE_PIXELS = 1056323868\n",
    "\n",
    "viewer = napari.Viewer()\n",
    "animation_widget = AnimationWidget(viewer)\n",
    "viewer.window.add_dock_widget(animation_widget, area=\"right\")\n",
    "viewer.scale_bar.visible = True\n",
    "\n",
    "napari.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "1545339 to 1545335"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "1549307 to 1548171"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "334.5559539794922\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import pickle\n",
    "\n",
    "start = time.time()\n",
    "with open(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/image_viterbrain_noattr_2.pickle\", \"rb\") as handle:\n",
    "    viterbi = pickle.load(handle)\n",
    "\n",
    "end = time.time()\n",
    "print(end - start)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "state = viterbi.comp_to_states[1545418][0]\n",
    "pt1 = viterbi.nxGraph.nodes[state][\"point1\"]\n",
    "state = viterbi.comp_to_states[1545432][0]\n",
    "pt2 = viterbi.nxGraph.nodes[state][\"point1\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[   54 17553 13759], [   54 17769 13527]\n"
     ]
    }
   ],
   "source": [
    "print(f\"{pt1}, {pt2}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[array([   54, 17553, 13759]),\n",
       " array([   54, 17565, 13743]),\n",
       " array([   54, 17589, 13721]),\n",
       " array([   54, 17605, 13696]),\n",
       " array([   54, 17607, 13693]),\n",
       " array([   54, 17623, 13671]),\n",
       " array([   54, 17626, 13632]),\n",
       " array([   54, 17693, 13594]),\n",
       " array([   54, 17719, 13567]),\n",
       " array([   54, 17723, 13558]),\n",
       " array([   54, 17724, 13555]),\n",
       " array([   54, 17730, 13549]),\n",
       " array([   54, 17727, 13532]),\n",
       " array([   54, 17745, 13527]),\n",
       " array([   54, 17769, 13527]),\n",
       " array([   54, 17782, 13510]),\n",
       " array([   54, 17769, 13527])]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "viterbi.fragment_path = \"/Users/thomasathey/Documents/mimlab/mouselight/BIL/image_labels_partial.zarr\"\n",
    "viterbi.shortest_path(pt1, pt2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import zarr\n",
    "from skimage import io\n",
    "from skimage import measure\n",
    "from tqdm import tqdm\n",
    "import h5py\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## convert ilastik output to labels in tif format"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "f = h5py.File(\n",
    "    \"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/191815_05401_CH1_Simple Segmentation.h5\",\n",
    "    \"r\",\n",
    ")\n",
    "pred = f.get(\"exported_data\")\n",
    "pred = pred[:, :, 0]\n",
    "mask = pred == 1\n",
    "mask = mask.astype(\"int32\")\n",
    "labels = measure.label(mask)\n",
    "io.imsave(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/54_comps.tif\", labels)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## write zarr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "zarr_labels = zarr.zeros((109, 28001, 19868), chunks=(1,1000,1000), dtype='i4')\n",
    "\n",
    "for z in tqdm(range(52, 57)):\n",
    "    labels = io.imread(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/\" + str(z) + \"_comps.tif\")\n",
    "    zarr_labels[z,:,:] = labels\n",
    "\n",
    "zarr.save('/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/labels_zarr.zarr', zarr_labels)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "zarr_image = zarr.zeros((109, 28001, 19868), chunks=(1,1000,1000), dtype='i4')\n",
    "\n",
    "for z in tqdm(range(52, 57)):\n",
    "    image = io.imread(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/191815_0\" + str(z) + \"01_CH1.tif\")\n",
    "    zarr_image[z,:,:] = image\n",
    "\n",
    "#zarr.save('/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/image_zarr.zarr', zarr_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import zarr\n",
    "zarr_image = zarr.open(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/image_labels_partial.zarr\")\n",
    "zarr_image.shape\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for x1 in range(0, 20000,2000):\n",
    "    x2 = np.amin([x1+2000, zarr_image.shape[2]])\n",
    "    im = zarr_image[52:57,:,x1:x2]\n",
    "    fname = \"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/ilastik/\" + str(x1) + \".tif\"\n",
    "    io.imsave(fname, im)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "zarr_probs = zarr.zeros((109, 28001, 19868), chunks=(1,1000,1000), dtype='float')\n",
    "for x1 in range(0, 20000,2000):\n",
    "    x2 = np.amin([x1+2000, zarr_image.shape[2]])\n",
    "    f = h5py.File(\n",
    "        \"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/ilastik/\" + str(x1) + \"_Probabilities.h5\",\n",
    "        \"r\",\n",
    "    )\n",
    "    pred = f.get(\"exported_data\")\n",
    "    probs = pred[:,:,:,0]\n",
    "    zarr_probs[52:57,:,x1:x2] = probs\n",
    "    break\n",
    "\n",
    "\n",
    "zarr.save('/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/probs_zarr.zarr', zarr_probs)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Viterbrain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from brainlit.algorithms.generate_fragments.state_generation import state_generation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sg = state_generation(\n",
    "    image_path=\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/image_zarr.zarr\",\n",
    "    ilastik_program_path=\"/Applications/ilastik-1.4.0b21-OSX.app/Contents/ilastik-release/run_ilastik.sh\",\n",
    "    ilastik_project_path=\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/ilastik/bil_slice.ilp\",\n",
    "    chunk_size=[5,1000,1000],\n",
    "    soma_coords=[],\n",
    "    parallel=8,\n",
    "    prob_path = \"/Users/thomasathey/Documents/mimlab/mouselight/BIL/labels/probs_zarr.zarr\",\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sg.compute_frags()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Check labels progress"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from skimage import io\n",
    "import napari\n",
    "import PIL.Image\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "im = io.imread(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/test_synaptomes/image.tif\")\n",
    "im_probs = io.imread(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/test_synaptomes/image_probs.tif\")\n",
    "im_labels = io.imread(\"/Users/thomasathey/Documents/mimlab/mouselight/BIL/test_synaptomes/image_labels.tif\")\n",
    "\n",
    "print(\"Displaying\")\n",
    "v = napari.Viewer()\n",
    "v.add_image(im, name=\"image\", contrast_limits=[0, 2**16])\n",
    "v.add_image(im_probs, name=\"probs\")\n",
    "v.add_labels(im_probs>0.25, name=\"0.15\")\n",
    "# v.add_labels(im_probs>0.25, name=\"0.25\")\n",
    "# v.add_labels(im_probs>0.5, name=\"0.5\")\n",
    "#v.add_labels(im_labels, name=\"labels\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import napari\n",
    "import PIL.Image\n",
    "import numpy as np\n",
    "from napari_animation import AnimationWidget\n",
    "import pickle\n",
    "from tqdm import tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "a = np.zeros((10,10))\n",
    "\n",
    "sys.getsizeof(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sys.getsizeof(viterbi)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sys.getsizeof(viterbi.nxGraph)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "5dc00d68ff54f8375e99934614da4863299fb9e10af4294c095b7f517546ff26"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 64-bit ('docs_env': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
